// This file is auto-generated by ./bin/rails stimulus:manifest:update

// Run that command whenever you add a new controller or create them with ./bin/rails generate stimulus controllerName

import { application } from './application';
import { callLogCallbacks } from '@common/is_local';

// https://youtu.be/qOptalp8zUY?t=362
import jsControllers from './**/*_controller.js';
import tsControllers from './**/*_controller.ts';

jsControllers.forEach((controller) => {
  application.register(controller.name, controller.module.default);
});

tsControllers.forEach((controller) => {
  let name = controller.name;

  name = name.replace('-controller.ts', '');

  application.register(name, controller.module.default);
});

callLogCallbacks();
